---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bjirekar6ity/public_html/
    - /bin/cp -f index.html $DEPLOYPATH
    - /bin/cp -f styles.css $DEPLOYPATH
    - /bin/cp -f app.js $DEPLOYPATH
    - /bin/cp -f .htaccess $DEPLOYPATH
